name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://rafaelcalleja/dind-buster:v0.1.8
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute next SemVer tag
        id: semver
        run: make next-version
