name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compute next SemVer tag
        id: semver
        uses: rafaelcalleja/dind-buster@v0.1.8
        with:
          args:
            - make
            - next-version