name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: docker://rafaelcalleja/dind-buster:v0.1.8
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute next SemVer tag
        id: release
        run: |
          export VERSION=$(make next-version)
          echo $VERSION > VERSION
          echo ::debug ::relase version ${VERSION}
          echo ::set-output name=tag_name::${VERSION}
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          release_name: Release ${{ steps.release.outputs.tag_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
